notes/urls.py
from django.urls import path
from . import views
app_name = 'notes'
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('home', views.home, name="home"),
    path('completed', views.completed, name="completed"),
    path('new-note', views.new, name="new_note"),
    path('edit/<int:id>/', views.edit, name="edit_note"),
    path('complete/<int:id>/', views.complete, name="complete_note"),
    path('delete/<int:id>/', views.delete, name="delete_note")
]

proj2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('notes.urls'))
]

notes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
# Create your models here.


class Note(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    colorText = models.CharField(max_length=7, default='#333333')
    colorBackground = models.CharField(max_length=7, default='#ffffff')
    fontSize = models.PositiveIntegerField(default=16, validators=[
        MaxValueValidator(30, 'Font size has to be less than or equal to 30'),
        MinValueValidator(5, 'Font size has to be bigger than or equal to 5')
    ])
    completed = models.BooleanField(default=False)
    userId = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def is_completed(self):
        return self.completed

notes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Note

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['name','content','colorText','colorBackground','fontSize']
        widgets = {
            'colorText':forms.TextInput(attrs={'type':'color'}),
            'colorBackground':forms.TextInput(attrs={'type':'color'})
        }

notes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from notes.forms import RegisterForm, NoteForm
from notes.models import Note
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(req):
    return render(req, 'notes/index.html')


def register(req):
    if req.method == 'POST':
        form = RegisterForm(req.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            pw = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=pw)
            login(req, user)
            return redirect('notes:index')
    else:
        form = RegisterForm()
    return render(req, 'notes/register.html', {'form': form})


@login_required
def new(req):
    if req.method == 'POST':
        form = NoteForm(req.POST)
        if form.is_valid():
            note = Note(name=form.cleaned_data.get('name'), content=form.cleaned_data.get('content'), colorText=form.cleaned_data.get(
                'colorText'), colorBackground=form.cleaned_data.get('colorBackground'), fontSize=form.cleaned_data.get('fontSize'), userId=req.user)
            note.save()
            return redirect('notes:home')
    else:
        form = NoteForm()
    return render(req, 'notes/newNote.html', {'form': form})


@login_required
def home(req):
    notes = Note.objects.filter(userId=req.user.id, completed=False)
    return render(req, 'notes/home.html', {'notes': notes})

@login_required
def completed(req):
    notes = Note.objects.filter(userId=req.user.id, completed=True)
    return render(req, 'notes/completed.html', {'notes': notes})


@login_required
def edit(req, id):
    try:
        note = Note.objects.get(id=id, userId=req.user.id, completed=False)
        if req.method == 'POST':
            form = NoteForm(req.POST)
            if form.is_valid():
                note.name = form.cleaned_data.get('name')
                note.content = form.cleaned_data.get('content')
                note.colorText = form.cleaned_data.get('colorText')
                note.colorBackground = form.cleaned_data.get('colorBackground')
                note.fontSize = form.cleaned_data.get('fontSize')
                note.save()
                return redirect('notes:home')
        else:
            form = NoteForm(instance=note)
            return render(req, 'notes/editNote.html', {'form': form, 'id': id})
    except:
        return redirect('notes:home')


@login_required
def complete(req, id):
    try:
        note = Note.objects.get(id=id, userId=req.user.id, completed=False)
        if req.method == 'POST':
            note.completed = True
            note.save()
            return redirect('notes:home')
        else:
            return render(req, 'notes/complete.html', {'note': note, 'id': id})
    except:
        return redirect('notes:home')


@login_required
def delete(req, id):
    try:
        note = Note.objects.get(id=id, userId=req.user.id)
        if req.method == 'POST':
            note.delete()
            return redirect('notes:home')
        else:
            return render(req, 'notes/delete.html', {'note': note, 'id': id})
    except:
        return redirect('notes:home')

notes/templates/notes/complete.html
{% extends 'notes/main.html' %}
{% load static %}

{% block content %}
<h1 class="notes-heading">Complete Note?</h1>
<div class="d-flex flex-column w-100">
    <div class="w-50 ps-5 pe-5 ms-auto me-auto">

        <div class="card card-note">
            <div class="card-body"
                style="color:{{note.colorText}};background-color:{{note.colorBackground}};font-size:{{note.fontSize}}px">
                <h5 class="card-title">{{note.name}}</h5>
                <p class="card-text">{{note.content}}</p>
            </div>
        </div>
        <form method="post" action="{% url 'notes:complete_note' note.id %}">
            {% csrf_token %}
            <button type=submit class="btn btn-secondary mt-4 ps-1 pe-1 w-25">
                Yes
            </button>
            <a class="btn btn-secondary mt-4 ps-1 pe-1 w-25" href="{% url 'notes:home' %}">
                No
            </a>
        </form>
    </div>

</div>
{% endblock %}

notes/templates/notes/completed.html
{% extends 'notes/main.html' %}
{% load static %}

{% block content %}
<div class="d-flex flex-column mt-3 mb-3">
    <h1 class="notes-heading">Your completed Notes</h1>
    <div class="row card-wrap">
        {% for note in notes %}
        <div class="col-3 mb-2 pe-2 ps-2 ">
            <div class="card card-note">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs fl-r">
                        <li class="nav-item">
                            <a class="nav-link card-head-link" href="{% url 'notes:delete_note' note.id %}">Delete</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body"
                    style="color:{{note.colorText}};background-color:{{note.colorBackground}};font-size:{{note.fontSize}}px">
                    <h5 class="card-title">{{note.name}}</h5>
                    <p class="card-text">{{note.content}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

notes/templates/notes/delete.html
{% extends 'notes/main.html' %}
{% load static %}

{% block content %}
<h1 class="notes-heading">Delete Note?</h1>
<div class="d-flex flex-column w-100">
    <div class="w-50 ps-5 pe-5 ms-auto me-auto">

        <div class="card card-note">
            <div class="card-body"
                style="color:{{note.colorText}};background-color:{{note.colorBackground}};font-size:{{note.fontSize}}px">
                <h5 class="card-title">{{note.name}}</h5>
                <p class="card-text">{{note.content}}</p>
            </div>
        </div>
        <form method="post" action="{% url 'notes:delete_note' note.id %}">
            {% csrf_token %}
            <button type=submit class="btn btn-secondary mt-4 ps-1 pe-1 w-25">
                Yes
            </button>
            <a class="btn btn-secondary mt-4 ps-1 pe-1 w-25" href="{% url 'notes:home' %}">
                No
            </a>
        </form>
    </div>

</div>
{% endblock %}

notes/templates/notes/editNote.html
{% extends 'notes/main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<h1 class="notes-heading">Create Note</h1>
<div class="d-flex flex-column w-100">

    <form method="post" action="{% url 'notes:edit_note' id %}" class="w-50 ps-5 pe-5 ms-auto me-auto">
        {% csrf_token %}
        <div class="form-group mt-2 mb-2">
            <label for="{{form.name.id_for_label}}">Title:</label>
            {{ form.name|add_class:'form-control' }}
            {% for error in form.name.errors %}
            <small class="form-text" style="color:red;">{{error}}</small>
            {% endfor %}
        </div>
        <div class="form-group mt-2 mb-2">
            <label for="{{form.content.id_for_label}}">Note:</label>
            {{ form.content|add_class:'form-control note-con-height' }}
            {% for error in form.content.errors %}
            <small class="form-text" style="color:red;">{{error}}</small>
            {% endfor %}
        </div>
        <div class="row mt-2 mb-2">
            <div class="form-group col d-flex flex-column">
                <label for="{{form.colorText.id_for_label}}">Text:</label>
                {{ form.colorText|add_class:'form-control h-100' }}
                {% for error in form.colorText.errors %}
                <small class="form-text" style="color:red;">{{error}}</small>
                {% endfor %}
            </div>
            <div class="form-group col d-flex flex-column">
                <label for="{{form.colorBackground.id_for_label}}">Background:</label>
                {{ form.colorBackground|add_class:'form-control h-100' }}
                {% for error in form.colorBackground.errors %}
                <small class="form-text" style="color:red;">{{error}}</small>
                {% endfor %}
            </div>
            <div class="form-group col d-flex flex-column">
                <label for="{{form.fontSize.id_for_label}}">Size:</label>
                {{ form.fontSize|add_class:'form-control h-100' }}
                {% for error in form.fontSize.errors %}
                <small class="form-text" style="color:red;">{{error}}</small>
                {% endfor %}
            </div>
            <button type="submit" class="col btn btn-secondary mt-4 ps-1 pe-1 w-25">Save</button>
        </div>
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
    </form>
</div>

{% endblock %}

notes/templates/notes/header.html
{% load static %}
    <div class="inner">
        <h3 class="masthead-brand">Notes</h3>
        <nav class="nav nav-masthead justify-content-center">
        {% if not user.is_authenticated %}
            <a class="nav-link" href="{% url 'notes:index' %}">Home</a>
            <a class="nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-link" href="{% url 'notes:register' %}">Register</a>
        {% else %}
            <a class="nav-link" href="{% url 'notes:home' %}">My Notes</a>
            <a class="nav-link" href="{% url 'notes:completed' %}">Completed Notes</a>
            <a class="nav-link" href="{% url 'notes:new_note' %}">New Note</a>
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% endif %}
        </nav>
    </div>

notes/templates/notes/home.html
{% extends 'notes/main.html' %}
{% load static %}

{% block content %}
<div class="d-flex flex-column mt-3 mb-3">
    <h1 class="notes-heading">Your notes</h1>
    <div class="row card-wrap">
        {% for note in notes %}
        <div class="col-3 mb-2 pe-2 ps-2 ">
            <div class="card card-note">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs fl-r">
                        <li class="nav-item">
                            <a class="nav-link card-head-link" href="{% url 'notes:edit_note' note.id %}">Edit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link card-head-link" href="{% url 'notes:delete_note' note.id %}">Delete</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link card-head-link"
                                href="{% url 'notes:complete_note' note.id %}">Complete</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body"
                    style="color:{{note.colorText}};background-color:{{note.colorBackground}};font-size:{{note.fontSize}}px">
                    <h5 class="card-title">{{note.name}}</h5>
                    <p class="card-text">{{note.content}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

notes/templates/notes/index.html
{% extends 'notes/main.html' %}
{% load static %}

{% block content %}
    <h1 class="notes-heading">Welcome to Notes</h1>
    <p class="lead">
        Please login so you can start creating your own notes
    </p>
{% endblock %}

notes/templates/notes/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>
        {% block title %}
        {{ page_title|default:"Notes" }}
        {% endblock title %}
    </title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body class="text-center">

    <div class="notes-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            {% include 'notes/header.html' %}
        </header>
        
        <main class="notes">
            {% block content %}
            <p>Whoops, something went wrong</p>
            {% endblock content %}
        </main>

        <footer class="mt-auto"></footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
    <script src="{% static 'script.js' %}"></script>
</body>

</html>

notes/templates/notes/newNote.html
{% extends 'notes/main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
{{form}}
{% endblock %}

notes/templates/notes/register.html
{% extends 'notes/main.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<h1 class="notes-heading">Register</h1>
<div class="d-flex flex-column w-100">
    <form method="post" action="{% url 'notes:register' %}" class="w-50 ps-5 pe-5 ms-auto me-auto">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group mt-2 mb-2">
            {{ field.label_tag }}
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <small class="form-text" style="color:red;">{{error}}</small>
            {% endfor %}
        </div>
        {% endfor %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        <button type="submit" class="btn btn-secondary mt-4 ps-1 pe-1 w-25">Sign up</button>
    </form>
</div>
{% endblock %}